// Copyright 2024 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Strategy module for basis capture and funding rate logic.
//!
//! This module implements the core strategy for capturing funding-rate and spot-perp basis
//! while maintaining delta neutrality. All calculations use integer arithmetic to ensure
//! deterministic execution in the zkVM.

/// Market data inputs required for strategy decisions
#[derive(Clone, Debug)]
pub struct MarketData {
    /// Spot ETH price in USD (scaled by 1e6 for precision, e.g., 3200000000 = $3200)
    pub spot_price: u128,
    /// Perpetual ETH price in USD (scaled by 1e6 for precision)
    pub perp_price: u128,
    /// Funding rate in basis points (scaled by 1e4, e.g., 15 = 0.0015%)
    pub funding_rate: i128,
    /// Funding interval in seconds (typically 8 hours = 28800)
    pub funding_interval_secs: u64,
    /// Liquidity score (0-1000, where 1000 = excellent liquidity)
    pub liquidity_score: u64,
    /// Timestamp of market data
    pub timestamp: u64,
}

/// Linear regression model for funding rate persistence prediction
#[derive(Clone, Debug)]
pub struct FundingModel {
    /// Model weights for features [funding_rate, volatility, time_decay]
    pub weights: [i128; 3],
    /// Bias term
    pub bias: i128,
    /// Minimum R² threshold for model confidence (0-10000, where 10000 = 100%)
    pub min_r_squared: u64,
}

/// Trading signal generated by the strategy
#[derive(Clone, Debug)]
pub struct StrategySignal {
    /// Whether to enter position (true) or exit/stay out (false)
    pub enter_position: bool,
    /// Target position size in USD (scaled by 1e6)
    pub position_size: u128,
    /// Predicted funding rate for next period (basis points)
    pub predicted_funding: i128,
    /// Model confidence score (0-10000, where 10000 = 100%)
    pub confidence: u64,
    /// Basis spread (perp_price - spot_price) in basis points
    pub basis_spread: i128,
}

impl MarketData {
    /// Calculate the basis spread in basis points
    pub fn basis_spread_bps(&self) -> i128 {
        if self.spot_price == 0 {
            return 0;
        }
        // Calculate (perp_price - spot_price) / spot_price * 10000
        let price_diff = self.perp_price as i128 - self.spot_price as i128;
        (price_diff * 10000) / (self.spot_price as i128)
    }

    /// Calculate annualized funding rate in basis points
    pub fn annualized_funding_bps(&self) -> i128 {
        if self.funding_interval_secs == 0 {
            return 0;
        }
        // Convert to annual rate: funding_rate * (365 * 24 * 3600) / funding_interval_secs
        const SECONDS_PER_YEAR: u64 = 365 * 24 * 3600;
        (self.funding_rate * SECONDS_PER_YEAR as i128) / self.funding_interval_secs as i128
    }

    /// Check if market conditions are suitable for basis capture
    pub fn is_suitable_for_capture(&self, min_funding_bps: i128, min_liquidity: u64) -> bool {
        let annualized_funding = self.annualized_funding_bps();
        
        // Require positive funding and sufficient liquidity
        annualized_funding >= min_funding_bps && self.liquidity_score >= min_liquidity
    }
}

impl FundingModel {
    /// Create a default funding persistence model
    pub fn default_model() -> Self {
        Self {
            // Default weights: [persistence, volatility_factor, time_decay]
            weights: [8000, -2000, -500], // Higher persistence weight, negative volatility impact
            bias: 1000,
            min_r_squared: 6000, // 60% minimum R²
        }
    }

    /// Predict funding rate persistence using linear regression
    pub fn predict_funding_persistence(
        &self, 
        current_funding: i128, 
        volatility: u64,
        time_factor: u64
    ) -> (i128, u64) {
        // Features: [current_funding, volatility, time_factor]
        let features = [current_funding, volatility as i128, time_factor as i128];
        
        // Linear regression: y = w1*x1 + w2*x2 + w3*x3 + bias
        let mut prediction = self.bias;
        for i in 0..3 {
            prediction += self.weights[i] * features[i] / 10000; // Scale weights
        }
        
        // Calculate confidence based on feature alignment with model
        let confidence = self.calculate_confidence(current_funding, volatility);
        
        (prediction, confidence)
    }

    /// Calculate model confidence based on input features
    fn calculate_confidence(&self, funding_rate: i128, volatility: u64) -> u64 {
        // Higher confidence for:
        // - Moderate funding rates (not extreme)
        // - Lower volatility
        let funding_factor = if funding_rate.abs() > 5000 { 5000 } else { 10000 - funding_rate.abs() as u64 };
        let volatility_factor = if volatility > 5000 { 0 } else { 10000 - volatility };
        
        ((funding_factor + volatility_factor) / 2).min(10000)
    }
}

/// Core strategy logic for basis capture decisions
pub struct BasisCaptureStrategy {
    /// Minimum funding rate threshold (basis points)
    pub min_funding_threshold: i128,
    /// Minimum liquidity score required
    pub min_liquidity_score: u64,
    /// Maximum position size as percentage of capital (basis points)
    pub max_position_size_bps: u64,
    /// Funding persistence model
    pub funding_model: FundingModel,
}

impl BasisCaptureStrategy {
    /// Create strategy with default parameters
    pub fn default() -> Self {
        Self {
            min_funding_threshold: 500, // 5% annual funding minimum
            min_liquidity_score: 700,   // 70% liquidity threshold
            max_position_size_bps: 10000, // 100% of capital max
            funding_model: FundingModel::default_model(),
        }
    }

    /// Generate trading signal based on market data
    pub fn generate_signal(
        &self, 
        market_data: &MarketData,
        current_position_size: u128,
        available_capital: u128
    ) -> StrategySignal {
        let basis_spread = market_data.basis_spread_bps();
        let annualized_funding = market_data.annualized_funding_bps();
        
        // Check if conditions are suitable
        if !market_data.is_suitable_for_capture(
            self.min_funding_threshold, 
            self.min_liquidity_score
        ) {
            return StrategySignal {
                enter_position: false,
                position_size: 0,
                predicted_funding: annualized_funding,
                confidence: 0,
                basis_spread,
            };
        }

        // Predict funding persistence
        let volatility = self.estimate_volatility(market_data);
        let time_factor = self.calculate_time_factor(market_data.timestamp);
        let (predicted_funding, model_confidence) = self.funding_model
            .predict_funding_persistence(market_data.funding_rate, volatility, time_factor);

        // Calculate optimal position size
        let target_size = self.calculate_position_size(
            annualized_funding,
            model_confidence,
            available_capital,
            current_position_size
        );

        // Decision logic: enter if funding is attractive and model is confident
        let should_enter = annualized_funding >= self.min_funding_threshold 
            && model_confidence >= self.funding_model.min_r_squared
            && target_size > 0;

        StrategySignal {
            enter_position: should_enter,
            position_size: target_size,
            predicted_funding,
            confidence: model_confidence,
            basis_spread,
        }
    }

    /// Estimate market volatility from price data (simplified)
    fn estimate_volatility(&self, market_data: &MarketData) -> u64 {
        // Simplified volatility estimate based on basis spread
        // In production, this would use historical price data
        let spread_abs = market_data.basis_spread_bps().abs() as u64;
        (spread_abs * 100).min(10000) // Cap at 100%
    }

    /// Calculate time factor for model input
    fn calculate_time_factor(&self, timestamp: u64) -> u64 {
        // Time-based decay factor (simplified)
        // In production, this would consider funding reset times
        const HOUR: u64 = 3600;
        let hours_since_funding = (timestamp % (8 * HOUR)) / HOUR;
        ((8 - hours_since_funding) * 1000).min(8000) // 0-8000 range
    }

    /// Calculate optimal position size based on Kelly criterion principles
    fn calculate_position_size(
        &self,
        expected_return: i128,
        confidence: u64,
        available_capital: u128,
        current_size: u128
    ) -> u128 {
        if expected_return <= 0 || confidence < 5000 { // Less than 50% confidence
            return 0;
        }

        // Kelly fraction approximation: f* = (bp - q) / b
        // Where b = odds, p = win probability, q = lose probability
        // Simplified to: position_size = (confidence / 10000) * max_size
        let confidence_factor = confidence.min(8000); // Cap at 80% for safety
        let max_size = (available_capital * self.max_position_size_bps as u128) / 10000;
        
        (max_size * confidence_factor as u128) / 10000
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_market_data_calculations() {
        let market_data = MarketData {
            spot_price: 3200_000000, // $3200
            perp_price: 3208_000000, // $3208
            funding_rate: 15,        // 0.0015%
            funding_interval_secs: 28800, // 8 hours
            liquidity_score: 800,
            timestamp: 1640995200, // Jan 1, 2022
        };

        // Test basis spread calculation
        let basis_bps = market_data.basis_spread_bps();
        assert_eq!(basis_bps, 25); // (3208-3200)/3200 * 10000 = 25 bps

        // Test annualized funding rate
        let annualized = market_data.annualized_funding_bps();
        // 0.0015% * 3 times per day * 365 days = 16.425% annually
        assert!(annualized > 1600 && annualized < 1700);
    }

    #[test]
    fn test_funding_model_prediction() {
        let model = FundingModel::default_model();
        let (prediction, confidence) = model.predict_funding_persistence(15, 2000, 4000);
        
        assert!(prediction > 0); // Should predict positive persistence
        assert!(confidence > 5000); // Should have reasonable confidence
    }

    #[test]
    fn test_strategy_signal_generation() {
        let strategy = BasisCaptureStrategy::default();
        let market_data = MarketData {
            spot_price: 3200_000000,
            perp_price: 3208_000000,
            funding_rate: 25, // Higher funding rate
            funding_interval_secs: 28800,
            liquidity_score: 800,
            timestamp: 1640995200,
        };

        let signal = strategy.generate_signal(&market_data, 0, 1000_000000); // $1000 available
        
        assert!(signal.confidence > 0);
        assert!(signal.basis_spread > 0);
    }
}