[package]
name = "vrbca-app"
version.workspace = true 
edition.workspace = true
publish = false

[dependencies]
# Workspace dependencies
guests.workspace = true

# External dependencies
anyhow.workspace = true
tokio = { workspace = true, features = ["full"] }
hex.workspace = true

[[bin]]
name = "app"
path = "src/main.rs"
